---
- hosts: webservers
  remote_user: root
  sudo: yes
  sudo_user: azure-admin
  gather_facts: no
  tasks:
  - name: Install Apache
    apt: name=apache2 state=present
    become_user: root
  - name: Start Apache
    service: name=apache2 state=started
    become_user: root
  
- hosts: dbservers
  remote_user: root
  sudo: yes
  sudo_user: azure-admin
  gather_facts: no
  tasks:
  - name: Install MySql
    apt: name=mysql-server state=present
  - name: Start MySql
    service: name=mysql state=started
  #- name: Deploy Apache configuration file
  #  copy: src=/ansible/files/conf/httpd.conf
  #        dest=/etc/httpd/conf